services:
  site:
    env_file:
      - .env
    build:
      context: ./site
      args:
        - HUGO_PARAMS_formSubmitEndpoint=http://localhost:8888/
    ports:
      - "8080:80"
    environment:
      - PORT=80
    depends_on:
      - contact-backend

  contact-backend:
    env_file:
      - .env
    build:
      context: ./contact-backend
    ports:
      - "8888:8080"
    environment:
      - PORT=8080 
      - ALLOWED_ORIGIN=http://localhost:8080

  blog-signup:
    env_file:
      - .env
    build:
      context: ./blog-signup
    ports:
      - "8081:8080"
    environment:
      - PORT=8080