version: '3.8'

services:
  site:
    build:
      context: ./site
      args:
        - HUGO_PARAMS_formSubmitEndpoint=http://localhost:8888/
    ports:
      - "8080:80"
    environment:
      - PORT=80
    depends_on:
      - contact-backend

  contact-backend:
    build:
      context: ./contact-backend
    ports:
      - "8888:8080"
    environment:
      - PORT=8080 
      - ALLOWED_ORIGIN=http://localhost:8080