baseURL = 'https://epistemic.technology'
languageCode = 'en-us'
title = 'Epistemic Technology'
theme = 'ETBASIC'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
      unsafe = true  # This allows raw HTML

[params]
  formSubmitEndpoint = "http://localhost:8080/" 
  subscribeSubmitEndpoint = "http://localhost:8081/signup"
  subscribeConfirmEndpoint = "http://localhost:8081/confirm"