baseURL = 'https://epistemic.technology'
languageCode = 'en-US'
title = 'Epistemic Technology'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  # Use getenv with a default value as fallback
  formSubmitEndpoint ="http://localhost:8080/" 